
from app.adapters import gemini, pgvector, pg
from app.utils import scoring, mmr
import logging

logger = logging.getLogger(__name__)

async def hybrid_retrieve(persona: dict, use_vector_search: bool = False) -> list[dict]:
    """
    NEW APPROACH: Structured SQL search using LLM-generated WHERE conditions.
    
    Instead of vector/keyword search, uses field-specific filters generated by LLM
    to directly query the database with precise WHERE clauses.
    
    Args:
        persona: Persona dictionary containing search_filters
        use_vector_search: If True, also perform vector search and blend (legacy mode)
    """
    logger.info("=" * 60)
    logger.info("2️⃣ Structured Search 시작 (LLM 생성 SQL 조건)")
    logger.info("=" * 60)
    
    persona_data = persona.get("persona", {})
    search_filters = persona_data.get("search_filters", {})
    
    if not search_filters:
        logger.warning("⚠️  No search_filters found in persona, falling back to legacy search")
        # Fallback to old method if search_filters not available
        return await _legacy_hybrid_retrieve(persona, use_vector_search)
    
    # Convert Pydantic model to dict if needed
    if hasattr(search_filters, 'model_dump'):
        search_filters = search_filters.model_dump()
    
    # Remove None values
    search_filters = {k: v for k, v in search_filters.items() if v is not None}
    
    if not search_filters:
        logger.warning("⚠️  search_filters is empty, returning empty results")
        return []
    
    logger.info("🔍 [Step 1] Structured SQL Search 실행 중...")
    logger.info(f"   → Filters: {list(search_filters.keys())}")
    
    try:
        # Use structured_search with LLM-generated filters
        results = await pg.structured_search(search_filters, k=30)
        logger.info(f"   ✅ Structured search 완료: {len(results)}개 결과")
        
        if results:
            top_scores = [f"{r.get('score', 0):.4f}" for r in results[:3]]
            logger.info(f"   📊 상위 3개 점수: {top_scores}")
        
        # Optional: Apply vector search for additional relevance
        if use_vector_search and len(results) > 0:
            logger.info("🔍 [Step 2] Vector Search 보조 실행 중...")
            query_text = persona_data.get("query_text", "")
            if query_text:
                try:
                    query_vector = await gemini.embed_query(query_text)
                    vec_results = await pgvector.vector_topk(query_vector, k=20)
                    
                    if vec_results:
                        logger.info(f"   ✅ Vector search 보조 결과: {len(vec_results)}개")
                        # Blend with structured results using RRF
                        blended = scoring.rrf_fusion(results, vec_results, k=60)
                        results = blended
                        logger.info(f"   ✅ RRF Blended 완료: {len(results)}개")
                except Exception as e:
                    logger.warning(f"   ⚠️  Vector search 실패, structured results만 사용: {e}")
        
        logger.info("=" * 60)
        return results[:12]  # Return top 12
        
    except Exception as e:
        logger.error(f"   ❌ Structured search 실패: {e}", exc_info=True)
        return []


async def _legacy_hybrid_retrieve(persona: dict, use_vector_search: bool = True) -> list[dict]:
    """
    Legacy hybrid retrieval method (kept for backward compatibility).
    """
    logger.info("⚠️  Using legacy hybrid retrieval")
    # ... (keep old implementation as fallback)
    return []
